name: SunflowerFields
main: me.fromgate.sunflowerfields.SunflowerFields
version: 1.0.1
author: fromgate, fromgate@gmail.com
commands:
   sunflower:
      aliases: [sflower]
      description: 
      usage: |
           /sunflower reload